import { test, before, after } from "node:test";
import assert from "node:assert/strict";
import crypto from "node:crypto";
import pool from "../src/config/database.js";
import { startTestServer, seedUsers } from "./setup.js";
import { authHeader, apiRequest, buildCreatePayload, buildPhotoForm } from "./gate-pass-helpers.js";

// Behavioural coverage for the smaller confirmed audit findings, so each one
// fails loudly if it comes back. The larger findings have their own files.

let server;
let users;
let ceoToken;
let managerToken;
let teamLeadToken;
let guardToken;
let hrToken;

before(async () => {
  server = await startTestServer();
  users = await seedUsers();
  ceoToken = await authHeader(server.baseUrl, "ceo@test.eset.local");
  managerToken = await authHeader(server.baseUrl, "manager@test.eset.local");
  teamLeadToken = await authHeader(server.baseUrl, "teamlead@test.eset.local");
  guardToken = await authHeader(server.baseUrl, "guard@test.eset.local");
  hrToken = await authHeader(server.baseUrl, "hr@test.eset.local");
});

after(async () => {
  await server.close();
  await pool.end();
});

test("a cross-site denial names the record it refused, not employees", async () => {
  // resolveCreateSiteId is shared by Employees, Departments, Positions,
  // Drivers and Vehicles, and told all of them "You can only create employees
  // within your own site" — so a Site Manager refused a cross-site VEHICLE was
  // told about employees.
  const vehicle = await apiRequest(server.baseUrl, "POST", "/api/v1/vehicles", {
    token: managerToken,
    body: { registrationNumber: `XSITE-${crypto.randomBytes(3).toString("hex")}`, siteId: users.otherSite },
  });
  assert.equal(vehicle.status, 403);
  assert.match(vehicle.body.error.message, /vehicles within your own site/i);
  assert.ok(!/employees/i.test(vehicle.body.error.message), "the message must not mention employees");

  const driver = await apiRequest(server.baseUrl, "POST", "/api/v1/drivers", {
    token: managerToken,
    body: { name: "Cross Site", phone: "+923001234567", siteId: users.otherSite },
  });
  assert.equal(driver.status, 403);
  assert.match(driver.body.error.message, /drivers within your own site/i);

  // And the Employee path still says employees, because there it is correct.
  const employee = await apiRequest(server.baseUrl, "POST", "/api/v1/employees", {
    token: hrToken,
    body: {
      employeeCode: `XS-${crypto.randomBytes(2).toString("hex").toUpperCase()}`,
      fullLegalName: "Cross Site Employee",
      joiningDate: "2026-02-01",
      siteId: users.otherSite,
    },
  });
  assert.equal(employee.status, 403);
  assert.match(employee.body.error.message, /employees within your own site/i);
});

test("creating an employee returns the same department and position the next read does", async () => {
  // The create response forced department/position to null even though the
  // initial assignment was created from them, so a client rendering the new
  // employee from that response showed a blank department.
  const code = `DTO-${crypto.randomBytes(3).toString("hex").toUpperCase()}`;
  const created = await apiRequest(server.baseUrl, "POST", "/api/v1/employees", {
    token: hrToken,
    body: {
      employeeCode: code,
      fullLegalName: "Projection Consistency",
      joiningDate: "2026-03-01",
      departmentId: users.departmentA,
    },
  });
  assert.equal(created.status, 201, JSON.stringify(created.body));
  assert.equal(created.body.data.departmentId, users.departmentA, "the create response must report the assignment");
  assert.ok(created.body.data.departmentName, "and resolve its name, as the detail endpoint does");

  const detail = await apiRequest(server.baseUrl, "GET", `/api/v1/employees/${created.body.data.id}`, {
    token: hrToken,
  });
  assert.deepEqual(created.body.data, detail.body.data, "create and detail must agree exactly");
});

test("a completion document that is still generating is 503, not 404", async () => {
  // 404 made "still being generated by the outbox" indistinguishable from
  // "no such Gate Pass / not yours", so a Guard who finished a return and
  // tapped straight through saw a not-found error for a document on its way.
  const created = await apiRequest(server.baseUrl, "POST", "/api/v1/gate-passes", {
    token: teamLeadToken,
    body: buildCreatePayload({ issuingDepartmentId: users.departmentA }),
  });
  const id = created.body.data.gatePass?.id || created.body.data.id;

  await apiRequest(server.baseUrl, "POST", `/api/v1/gate-passes/${id}/submit`, { token: teamLeadToken });
  await apiRequest(server.baseUrl, "POST", `/api/v1/gate-passes/${id}/approve`, { token: managerToken });
  await apiRequest(server.baseUrl, "POST", `/api/v1/gate-passes/${id}/exit`, {
    token: guardToken,
    body: buildPhotoForm({ odometer: "1000" }),
    isForm: true,
  });
  await apiRequest(server.baseUrl, "POST", `/api/v1/gate-passes/${id}/return`, {
    token: guardToken,
    body: buildPhotoForm({ odometer: "1200" }),
    isForm: true,
  });

  // The outbox job has not run yet in this test process.
  const pending = await apiRequest(server.baseUrl, "GET", `/api/v1/gate-passes/${id}/completion-pdf`, {
    token: managerToken,
  });
  assert.equal(pending.status, 503, "a pending document must say 'ask again', not 'not found'");
  assert.equal(pending.body.error.code, "SERVICE_UNAVAILABLE");
  assert.match(pending.body.error.message, /still being generated/i);

  // A Gate Pass the caller genuinely may not see is still an ordinary 404, so
  // the two cases stay distinguishable in both directions.
  const otherSiteToken = await authHeader(server.baseUrl, "teamlead-othersite@test.eset.local");
  const foreign = await apiRequest(server.baseUrl, "GET", `/api/v1/gate-passes/${id}/completion-pdf`, {
    token: otherSiteToken,
  });
  assert.equal(foreign.status, 404);
});

test("the duplicate pre-check endpoint answers before an employee is created", async () => {
  // Reachable from Add Employee now. The authoritative check remains the
  // transactional one at create time; this is the advisory the endpoint was
  // built for.
  const name = `Advisory ${crypto.randomBytes(3).toString("hex")}`;
  const code = `ADV-${crypto.randomBytes(3).toString("hex").toUpperCase()}`;

  const before = await apiRequest(server.baseUrl, "POST", "/api/v1/employees/check-duplicates", {
    token: hrToken,
    body: { fullLegalName: name, siteId: users.mainSite },
  });
  assert.equal(before.status, 200);
  assert.equal(before.body.data.matches.length, 0, "nothing exists yet");

  await apiRequest(server.baseUrl, "POST", "/api/v1/employees", {
    token: hrToken,
    body: { employeeCode: code, fullLegalName: name, joiningDate: "2026-04-01" },
  });

  const after = await apiRequest(server.baseUrl, "POST", "/api/v1/employees/check-duplicates", {
    token: hrToken,
    body: { fullLegalName: name, siteId: users.mainSite },
  });
  assert.equal(after.status, 200);
  assert.ok(
    after.body.data.matches.some((match) => match.employee_code === code),
    "the pre-check must now report the existing record",
  );
});

test("business history is readable, and self-access needs no extra permission", async () => {
  const code = `HIS-${crypto.randomBytes(3).toString("hex").toUpperCase()}`;
  const created = await apiRequest(server.baseUrl, "POST", "/api/v1/employees", {
    token: hrToken,
    body: { employeeCode: code, fullLegalName: "History Reader", joiningDate: "2026-05-01" },
  });
  const employeeId = created.body.data.id;

  const history = await apiRequest(server.baseUrl, "GET", `/api/v1/employees/${employeeId}/history`, {
    token: hrToken,
  });
  assert.equal(history.status, 200);
  assert.ok(
    history.body.data.some((entry) => entry.event_type === "EMPLOYEE_CREATED"),
    "creation must be recorded in the history the UI now reads",
  );

  // An actor with no workforce visibility cannot read someone else's history.
  const employeeToken = await authHeader(server.baseUrl, "employee@test.eset.local");
  const denied = await apiRequest(server.baseUrl, "GET", `/api/v1/employees/${employeeId}/history`, {
    token: employeeToken,
  });
  assert.equal(denied.status, 403);
});

test("a CURRENT contract can be marked ended, and a finalized one is still never rewritten", async () => {
  const code = `CON-${crypto.randomBytes(3).toString("hex").toUpperCase()}`;
  const employee = await apiRequest(server.baseUrl, "POST", "/api/v1/employees", {
    token: hrToken,
    body: { employeeCode: code, fullLegalName: "Contract Lifecycle", joiningDate: "2026-06-01" },
  });
  const employeeId = employee.body.data.id;

  const draft = await apiRequest(server.baseUrl, "POST", `/api/v1/employees/${employeeId}/contracts`, {
    token: ceoToken,
    body: { kind: "ORIGINAL" },
  });
  assert.equal(draft.status, 201, JSON.stringify(draft.body));
  const contractId = draft.body.data.id;

  await apiRequest(server.baseUrl, "PATCH", `/api/v1/employees/${employeeId}/contracts/${contractId}`, {
    token: ceoToken,
    body: { effectiveStartDate: "2026-06-01", termsSummary: "Standard terms" },
  });

  const form = new FormData();
  form.append("file", new Blob([Buffer.from("%PDF-1.4\ntest\n%%EOF")], { type: "application/pdf" }), "c.pdf");
  await apiRequest(server.baseUrl, "POST", `/api/v1/employees/${employeeId}/contracts/${contractId}/file`, {
    token: ceoToken,
    body: form,
    isForm: true,
  });
  const finalized = await apiRequest(
    server.baseUrl,
    "POST",
    `/api/v1/employees/${employeeId}/contracts/${contractId}/finalize`,
    { token: ceoToken },
  );
  assert.equal(finalized.status, 200, JSON.stringify(finalized.body));

  const transitioned = await apiRequest(
    server.baseUrl,
    "POST",
    `/api/v1/employees/${employeeId}/contracts/${contractId}/transition`,
    { token: ceoToken, body: { status: "TERMINATED" } },
  );
  assert.equal(transitioned.status, 200, JSON.stringify(transitioned.body));
  assert.equal(transitioned.body.data.status, "TERMINATED");

  // Terminal is terminal: a second transition is refused.
  const again = await apiRequest(
    server.baseUrl,
    "POST",
    `/api/v1/employees/${employeeId}/contracts/${contractId}/transition`,
    { token: ceoToken, body: { status: "EXPIRED" } },
  );
  assert.equal(again.status, 409);

  // And the finalized contract's own terms are still frozen.
  await assert.rejects(
    pool.query("UPDATE employee_contracts SET terms_summary = 'rewritten' WHERE id = $1", [contractId]),
    /immutable|not permitted|cannot/i,
  );
});
