import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { useGatePass } from "../hooks/useGatePass.js";
import { useAuth } from "../../../core/auth/AuthContext.jsx";
import {
  submitGatePass,
  approveGatePass,
  rejectGatePass,
  cancelGatePass,
  downloadGatePassPdf,
  downloadGatePassCompletionPdf,
  downloadGatePassFile,
} from "../api.js";
import { GatePassStatusBadge } from "../components/GatePassStatusBadge.jsx";
import { AuditTimeline } from "../components/AuditTimeline.jsx";
import { Button } from "../../../shared/components/Button.jsx";
import { LoadingState } from "../../../shared/components/StatePanel.jsx";
import { RecordErrorState } from "../../../shared/components/RecordErrorState.jsx";
import { ConfirmActionDialog } from "../../../shared/components/ConfirmActionDialog.jsx";
import { ReasonActionDialog } from "../../../shared/components/ReasonActionDialog.jsx";
import { formatEnumLabel } from "../../../shared/utilities/format.js";
import { formatDate, formatDateTime } from "../../../shared/utilities/datetime.js";
import styles from "./GatePassDetailPage.module.css";

const EDITABLE_STATUSES = ["DRAFT"];
const SUBMITTABLE_STATUSES = ["DRAFT"];
const APPROVE_REJECT_STATUSES = ["DRAFT", "PENDING_APPROVAL"];
const CANCELLABLE_STATUSES = ["DRAFT", "PENDING_APPROVAL", "APPROVED"];
const PDF_AVAILABLE_STATUSES = ["APPROVED", "VEHICLE_OUTSIDE", "COMPLETED"];

// Bounded polling for the demo blocker fix: approval commits immediately,
// but the PDF is generated by a durable background job that may take up
// to the outbox's poll interval to run (see docs/DECISIONS.md). The UI
// must show "generating" and re-check, never show a stale "View PDF"
// button that 404s. Capped, not indefinite — if it's still not ready
// after this many checks, something's actually wrong and hammering the
// server won't fix it.
const DOCUMENT_POLL_INTERVAL_MS = 3000;
const DOCUMENT_POLL_MAX_ATTEMPTS = 20;

function DetailField({ label, value }) {
  return (
    <div className={styles.detailItem}>
      <dt>{label}</dt>
      <dd>{value || "—"}</dd>
    </div>
  );
}

export function GatePassDetailPage() {
  const { id } = useParams();
  const navigate = useNavigate();
  const { hasPermission } = useAuth();
  const { gatePass, status, error, reload } = useGatePass(id);

  const [activeDialog, setActiveDialog] = useState(null);
  const [pdfLoading, setPdfLoading] = useState(false);
  const [completionPdfLoading, setCompletionPdfLoading] = useState(false);
  const [pdfError, setPdfError] = useState(null);
  const [pollAttempts, setPollAttempts] = useState(0);
  const [evidenceLoadingId, setEvidenceLoadingId] = useState(null);
  const [evidenceError, setEvidenceError] = useState(null);

  const isDocumentPending = PDF_AVAILABLE_STATUSES.includes(gatePass?.status) && gatePass?.documentReady === false;
  const documentPollExhausted = isDocumentPending && pollAttempts >= DOCUMENT_POLL_MAX_ATTEMPTS;

  useEffect(() => {
    if (!isDocumentPending) {
      return undefined;
    }

    if (pollAttempts >= DOCUMENT_POLL_MAX_ATTEMPTS) {
      return undefined;
    }

    const timer = setTimeout(() => {
      setPollAttempts((prev) => prev + 1);
      reload({ silent: true });
    }, DOCUMENT_POLL_INTERVAL_MS);

    return () => clearTimeout(timer);
    // Re-runs each time gatePass updates (including from the poll itself),
    // which is exactly what re-checking "is it ready yet, and are we still
    // in a state where it's expected to become ready" needs. pollAttempts
    // never needs resetting: it's only ever read while isDocumentPending
    // is also true, and status only ever moves forward for a given Gate
    // Pass, so "pending" can't become true again after going false.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isDocumentPending, pollAttempts, gatePass]);

  if (status === "loading") {
    return <LoadingState message="Loading Gate Pass…" />;
  }

  if (status === "error") {
    return <RecordErrorState error={error} onRetry={reload} fallback="Unable to load this Gate Pass." />;
  }

  const canEdit = EDITABLE_STATUSES.includes(gatePass.status) && hasPermission("gate_pass.edit_draft");
  const canSubmit = SUBMITTABLE_STATUSES.includes(gatePass.status) && hasPermission("gate_pass.submit");
  const canApprove = APPROVE_REJECT_STATUSES.includes(gatePass.status) && hasPermission("gate_pass.approve");
  const canReject = APPROVE_REJECT_STATUSES.includes(gatePass.status) && hasPermission("gate_pass.reject");
  const canCancel = CANCELLABLE_STATUSES.includes(gatePass.status) && hasPermission("gate_pass.cancel");
  // documentReady, not just status — status flips to APPROVED the instant
  // the transition commits, well before the background job that actually
  // generates the PDF has necessarily run (Fix: PDF readiness race).
  const canDownloadPdf = PDF_AVAILABLE_STATUSES.includes(gatePass.status) && gatePass.documentReady;

  async function handleSubmit() {
    await submitGatePass(id);
    await reload();
  }

  async function handleApprove() {
    await approveGatePass(id);
    await reload();
  }

  async function handleReject(reason) {
    await rejectGatePass(id, reason);
    await reload();
  }

  async function handleCancel(reason) {
    await cancelGatePass(id, reason);
    await reload();
  }

  async function handleDownloadPdf() {
    setPdfLoading(true);
    setPdfError(null);

    try {
      const blob = await downloadGatePassPdf(id);
      const url = URL.createObjectURL(blob);
      window.open(url, "_blank", "noopener");
      setTimeout(() => URL.revokeObjectURL(url), 60_000);
    } catch (downloadError) {
      setPdfError(downloadError.message || "Unable to download the PDF.");
    } finally {
      setPdfLoading(false);
    }
  }

  // The closure document, distinct from the approval PDF: real exit/return
  // times plus the outbound and inbound evidence sections. Offered only once
  // the pass is COMPLETED, and it may briefly 404 while the durable
  // generation job is still running — completion never waits on it.
  async function handleDownloadCompletionPdf() {
    setCompletionPdfLoading(true);
    setPdfError(null);

    try {
      const blob = await downloadGatePassCompletionPdf(id);
      const url = URL.createObjectURL(blob);
      window.open(url, "_blank", "noopener");
      setTimeout(() => URL.revokeObjectURL(url), 60_000);
    } catch (downloadError) {
      setPdfError(downloadError.message || "The completion document is not ready yet.");
    } finally {
      setCompletionPdfLoading(false);
    }
  }

  async function handleViewEvidence(fileId) {
    setEvidenceLoadingId(fileId);
    setEvidenceError(null);

    try {
      const blob = await downloadGatePassFile(id, fileId);
      const url = URL.createObjectURL(blob);
      window.open(url, "_blank", "noopener");
      setTimeout(() => URL.revokeObjectURL(url), 60_000);
    } catch (downloadError) {
      setEvidenceError(downloadError.message || "Unable to load the photo.");
    } finally {
      setEvidenceLoadingId(null);
    }
  }

  return (
    <div>
      <div className={styles.header}>
        <div className={styles.headingGroup}>
          <h1 className={styles.number}>{gatePass.gatePassNumber}</h1>
          <div className={styles.subtitle}>
            <GatePassStatusBadge status={gatePass.status} /> &nbsp;·&nbsp; Created{" "}
            {formatDateTime(gatePass.createdAt)}
          </div>
        </div>
        <div className={styles.actions}>
          {canEdit && (
            <Button variant="secondary" onClick={() => navigate(`/gate-passes/${id}/edit`)}>
              Edit
            </Button>
          )}
          {gatePass.status === "COMPLETED" && (
            <Button variant="secondary" onClick={handleDownloadCompletionPdf} loading={completionPdfLoading}>
              Completion Record
            </Button>
          )}
          {canDownloadPdf && (
            <Button variant="secondary" onClick={handleDownloadPdf} loading={pdfLoading}>
              View PDF
            </Button>
          )}
          {isDocumentPending && !documentPollExhausted && (
            <span className={styles.documentPending} role="status" aria-live="polite">
              <span className={styles.spinnerDot} aria-hidden="true" />
              Generating Gate Pass PDF…
            </span>
          )}
          {canCancel && (
            <Button variant="secondary" onClick={() => setActiveDialog("cancel")}>
              Cancel
            </Button>
          )}
          {canReject && (
            <Button variant="danger" onClick={() => setActiveDialog("reject")}>
              Reject
            </Button>
          )}
          {canApprove && <Button onClick={() => setActiveDialog("approve")}>Approve</Button>}
          {canSubmit && (
            <Button onClick={() => setActiveDialog("submit")}>Submit for Approval</Button>
          )}
        </div>
      </div>

      {pdfError && <p className={styles.pdfError}>{pdfError}</p>}
      {documentPollExhausted && (
        <p className={styles.pdfError}>
          The Gate Pass document is taking longer than expected to generate.{" "}
          <button type="button" className={styles.inlineLinkButton} onClick={() => reload()}>
            Check again
          </button>
        </p>
      )}

      <div className={styles.layout}>
        <div className={styles.mainColumn}>
          <div className={styles.section}>
            <h2 className={styles.sectionTitle}>Details</h2>
            <dl className={styles.detailGrid}>
              <DetailField label="Issuing Department" value={gatePass.issuingDepartmentName} />
              <DetailField label="Requested By" value={gatePass.requestedBy} />
              <DetailField label="Destination" value={gatePass.destination} />
              <DetailField label="Purpose" value={formatEnumLabel(gatePass.purpose)} />
              <DetailField label="Driver" value={`${gatePass.driverName} (${gatePass.driverPhone})`} />
              <DetailField label="Vehicle Registration" value={gatePass.vehicleRegistration} />
              <DetailField label="Job Order ID" value={gatePass.jobOrderId} />
              <DetailField
                label="Expected Return Date"
                value={formatDate(gatePass.expectedReturnDate)}
              />
              <DetailField label="Created By" value={gatePass.createdByName} />
              <DetailField label="Approved By" value={gatePass.approvedByName} />
              {gatePass.remarks && <DetailField label="Remarks" value={gatePass.remarks} />}
              {gatePass.rejectionReason && <DetailField label="Rejection Reason" value={gatePass.rejectionReason} />}
              {gatePass.cancellationReason && <DetailField label="Cancellation Reason" value={gatePass.cancellationReason} />}
            </dl>
          </div>

          <div className={styles.section}>
            <h2 className={styles.sectionTitle}>Items</h2>
            <div className={styles.tableWrapper}>
              <table className={styles.itemsTable}>
                <thead>
                  <tr>
                    <th>Description</th>
                    <th>Part Number</th>
                    <th>Quantity</th>
                    <th>Unit</th>
                  </tr>
                </thead>
                <tbody>
                  {gatePass.items.map((item) => (
                    <tr key={item.id}>
                      <td>{item.description}</td>
                      <td>{item.partNumber || "—"}</td>
                      <td>{item.quantity}</td>
                      <td>{item.unit || "—"}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {(gatePass.departureOdometer !== null || gatePass.returnOdometer !== null) && (
            <div className={styles.section}>
              <h2 className={styles.sectionTitle}>Gate Activity</h2>
              <dl className={styles.detailGrid}>
                <DetailField label="Departure Odometer" value={gatePass.departureOdometer} />
                <DetailField label="Departure Time" value={formatDateTime(gatePass.departureAt)} />
                <DetailField label="Return Odometer" value={gatePass.returnOdometer} />
                <DetailField label="Return Time" value={formatDateTime(gatePass.returnAt)} />
                <DetailField label="Distance" value={gatePass.distanceKm !== null ? `${gatePass.distanceKm} km` : null} />
                {gatePass.returnRemarks && <DetailField label="Return Remarks" value={gatePass.returnRemarks} />}
              </dl>
            </div>
          )}

          {(gatePass.departureEvidence || gatePass.returnEvidence) && (
            <div className={styles.section}>
              <h2 className={styles.sectionTitle}>Evidence</h2>
              {evidenceError && <p className={styles.pdfError}>{evidenceError}</p>}
              <div className={styles.evidenceGrid}>
                {gatePass.departureEvidence && (
                  <div className={styles.evidenceCard}>
                    <h3 className={styles.evidenceCardTitle}>Departure Evidence</h3>
                    <dl className={styles.detailGrid}>
                      <DetailField label="Odometer" value={gatePass.departureEvidence.odometer} />
                      <DetailField
                        label="Recorded"
                        value={formatDateTime(gatePass.departureEvidence.recordedAt)}
                      />
                      <DetailField label="Guard" value={gatePass.departureEvidence.recordedByName} />
                    </dl>
                    <Button
                      variant="secondary"
                      onClick={() => handleViewEvidence(gatePass.departureEvidence.fileId)}
                      loading={evidenceLoadingId === gatePass.departureEvidence.fileId}
                    >
                      View Photo
                    </Button>
                  </div>
                )}
                {gatePass.returnEvidence && (
                  <div className={styles.evidenceCard}>
                    <h3 className={styles.evidenceCardTitle}>Return Evidence</h3>
                    <dl className={styles.detailGrid}>
                      <DetailField label="Odometer" value={gatePass.returnEvidence.odometer} />
                      <DetailField
                        label="Recorded"
                        value={formatDateTime(gatePass.returnEvidence.recordedAt)}
                      />
                      <DetailField label="Guard" value={gatePass.returnEvidence.recordedByName} />
                    </dl>
                    <Button
                      variant="secondary"
                      onClick={() => handleViewEvidence(gatePass.returnEvidence.fileId)}
                      loading={evidenceLoadingId === gatePass.returnEvidence.fileId}
                    >
                      View Photo
                    </Button>
                  </div>
                )}
              </div>
            </div>
          )}
        </div>

        <div className={styles.section}>
          <h2 className={styles.sectionTitle}>Audit Timeline</h2>
          <AuditTimeline entries={gatePass.auditLog} />
        </div>
      </div>

      <ConfirmActionDialog
        open={activeDialog === "submit"}
        onClose={() => setActiveDialog(null)}
        title="Submit for approval?"
        message="This Gate Pass will move to Pending Approval and can no longer be edited."
        confirmLabel="Submit"
        onConfirm={handleSubmit}
      />
      <ConfirmActionDialog
        open={activeDialog === "approve"}
        onClose={() => setActiveDialog(null)}
        title="Approve this Gate Pass?"
        message="Approving will generate the issued Gate Pass PDF and notify the gate."
        confirmLabel="Approve"
        onConfirm={handleApprove}
      />
      <ReasonActionDialog
        open={activeDialog === "reject"}
        onClose={() => setActiveDialog(null)}
        title="Reject this Gate Pass?"
        message="Provide a reason for the requester."
        confirmLabel="Reject"
        onConfirm={handleReject}
      />
      <ReasonActionDialog
        open={activeDialog === "cancel"}
        onClose={() => setActiveDialog(null)}
        title="Cancel this Gate Pass?"
        message="This cannot be undone once the vehicle has left the site."
        confirmLabel="Cancel Gate Pass"
        onConfirm={handleCancel}
      />
    </div>
  );
}
